### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicNameValuePair

### ISSUE THREAD

**Issue by JasiekRadzik** [coinbase/coinbase-android-sdk#19]
Exception is thrown while calling OAuth.beginAuthorization(...). 
`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicNameValuePair;
        at org.apache.http.client.utils.URIBuilder.addParameter(URIBuilder.java:350)
        at com.coinbase.api.CoinbaseImpl.getAuthorizationUri(CoinbaseImpl.java:1135)
        at com.coinbase.android.sdk.OAuth.beginAuthorization(OAuth.java:36)
        at <...>.data.api.coinbase.CoinBaseAuth.startAuth(CoinBaseAuth.kt:17)
        at <...>.domain.login.LoginUserCase.startAuth(LoginUserCase.kt:18)
        at <...>.presentation.login.LoginViewModel.startAuth(LoginViewModel.kt:21)
        at <...>.presentation.login.LoginActivity$initView$1.onClick(LoginActivity.kt:28)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicNameValuePair" on path: DexPathList[[zip file "/data/app/<...>-2MN8xvV_HTBANhsukPUwFg==/base.apk"],nativeLibraryDirectories=[/data/app/<...>-2MN8xvV_HTBANhsukPUwFg==/lib/x86, /system/lib]]`

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
