### ISSUE TITLE
Manual build instructions fails with dex exception

### ISSUE THREAD

**Issue by jonalmeida** [coinbase/coinbase-android-sdk#5]
The current manual build instructions throws a multiple dex files exception.

Build instructions:
```
Manual

You can copy this library jar and all its dependency jars to a folder as follows:

git clone git@github.com:coinbase/coinbase-android-sdk.git
cd coinbase-android-sdk
mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=$YOUR_JAR_DIRECTORY
mvn package
cp target/coinbase-android-sdk-1.0.1.jar $YOUR_JAR_DIRECTORY
```

Error seen:
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/apache/http/annotation/GuardedBy;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

The library that causes this error is `httpclient-4.0.1.jar`. The fix is to remove it:
```
rm $YOUR_JAR_DIRECTORY/httpclient-4.0.1.jar
```

**Comment by aianus** [comment]
Thanks, updated README. I would highly suggest you use gradle instead of the manual method though.

**Comment by jonalmeida** [comment]
I was trying to use the patch that opened the Coinbase app if available. :)

**Comment by aianus** [comment]
Ah, for future reference you can run `mvn install` to install the dev version (1.0.2-SNAPSHOT) into your local maven repository and point your gradle at 'com.coinbase.android:coinbase-android-sdk:1.0.2-SNAPSHOT'

The Coinbase app does not yet support native authentication.
